game_management_system/game_catalogue/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('collection/<uuid:pk>', views.GameCollectionDetailView.as_view(), name = 'game-collection-detail'),
]

urlpatterns += [
    path('game/<uuid:pk>', views.GameDetailView.as_view(), name = 'game-detail'),
]

urlpatterns += [
    path('mycollection/', views.OwnedGamesByUserListView.as_view(), name='my-collection')
]

# Add Remove collections
urlpatterns += [
    path('collection/create/', views.GameCollectionCreate.as_view(), name='game-collection-create'),
    path('collection/<uuid:pk>/update/', views.GameCollectionUpdate.as_view(), name='game-collection-update'),
    path('collection/<uuid:pk>/delete/', views.GameCollectionDelete.as_view(), name='game-collection-delete'),
    ]

urlpatterns += [
    path('collection/<uuid:pk>/create/', views.GameCreate.as_view(), name='game-create'),
    path('game/<uuid:pk>/update/', views.GameUpdate.as_view(), name='game-update'),
    path('game/<uuid:pk>/delete/', views.GameDelete.as_view(), name='game-delete'),
    ]

game_management_system/game_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.forms import UserCreationForm


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('game_catalogue/', include('game_catalogue.urls')),
                  path('', RedirectView.as_view(url = 'game_catalogue/')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/success', views.user_signup_success, name = 'sign-up-success'),
                  path('accounts/', views.UserSignupView.as_view(), name = 'sign-up'),
              ] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

game_management_system/game_catalogue/models.py
from django.db import models

# Create your models here.

from django.urls import reverse
from django.contrib.auth.models import User
import uuid  # Required for unique book instances
from datetime import date


class GameCollection(models.Model):
    """Model representing a Game Collection genre."""
    collection_id = models.UUIDField(primary_key = True,  default = uuid.uuid4,
                                     help_text = "Unique collection identifier Id")
    collection_name = models.CharField(max_length = 200, help_text = 'Name of game collection')
    collection_created_date = models.DateField(null = True, blank = True, default=date.today)
    collection_description = models.TextField(max_length = 2000)
    owner = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, blank = True)

    def get_absolute_url(self):
        return reverse('game-collection-detail', args=[str(self.collection_id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.collection_name


class Game(models.Model):
    """Model representing an author."""
    game_id = models.UUIDField(primary_key = True,  default = uuid.uuid4,
                               help_text = "Unique game identifier Id")
    game_title = models.CharField(max_length=100)
    game_description = models.TextField(max_length=2000)
    game_category = models.CharField(max_length=200, null=True, default=None)
    game_rule = models.TextField(max_length=2000)
    game_created_date = models.DateField(null=True, blank=True, default=date.today)
    game_collection = models.ManyToManyField(GameCollection, help_text = "Game collection Game belongs to")

    RATING_CHOICES = (
        (1, "Very Bad"),
        (2, "Bad"),
        (3, "Neutral"),
        (4, "Good"),
        (5, "Very Good")
    )

    game_rating = models.IntegerField(choices = RATING_CHOICES, null=True)

    def get_absolute_url(self):
        return reverse('game-detail', args=[str(self.game_id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.game_id, self.game_title)

game_management_system/game_catalogue/views.py
from django.shortcuts import render

# Create your views here.

from game_catalogue.models import GameCollection, Game
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required


@login_required(login_url='/accounts/login/')
def index(request):
    """View function for home page of site."""

    # Number of collections
    num_collections = GameCollection.objects.filter(owner = request.user).count()
    num_games = Game.objects.filter(game_collection__owner = request.user).count()

    context = {
        'num_collections': num_collections,
        'num_games': num_games,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context = context)


class GameCollectionDetailView(generic.DetailView):
    model = GameCollection

    def get_parameter_value(self, parameter_key):
        try:
            value = self.request.GET.get(parameter_key, )
        except KeyError:
            value = None
        return value

    def get_context_data(self, **kwargs):
        context = super(GameCollectionDetailView, self).get_context_data(**kwargs)
        collection = self.get_object()
        name = self.get_parameter_value('game_name')
        category = self.get_parameter_value('game_category')
        description = self.get_parameter_value('game_description')

        if name and name != "":
            context['filtered_games'] = Game.objects.filter(game_collection = collection,
                                                            game_title__contains = name)
        elif category and category != "":
            context['filtered_games'] = Game.objects.filter(game_collection = collection,
                                                            game_category__contains = category)
        elif description and description != "":
            context['filtered_games'] = Game.objects.filter(game_collection = collection,
                                                            game_description__contains = description)
        else:
            context['filtered_games'] = Game.objects.filter(game_collection = collection)
        return context


class OwnedGamesByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = GameCollection
    template_name = 'game_catalogue/gamecollection_list_owned_user.html'
    paginate_by = 10

    def get_queryset(self):
        return GameCollection.objects.filter(owner = self.request.user)


class GameDetailView(generic.DetailView):
    model = Game


class GameCollectionCreate(CreateView):
    model = GameCollection
    fields = ['collection_name', 'collection_description']

    def form_valid(self, form):
        owner = self.request.user
        form.instance.owner = owner
        return super(GameCollectionCreate, self).form_valid(form)


class GameCollectionUpdate(UpdateView):
    model = GameCollection
    fields = ['collection_name', 'collection_description']


class GameCollectionDelete(DeleteView):
    model = GameCollection
    success_url = reverse_lazy('my-collection')


class GameCreate(CreateView):
    model = Game
    fields = ['game_title', 'game_description', 'game_rule', 'game_created_date', 'game_category',
              'game_rating']

    def get_initial(self):
        return {"game_collection": self.kwargs.get("pk")}

    def get_success_url(self):
        return reverse('game-collection-detail', args=[str(self.get_initial()['game_collection'])])

    def form_valid(self, form):
        owner = self.request.user
        form.instance.owner = owner
        form.save()
        game_collection = GameCollection.objects.get(collection_id=str(self.get_initial()['game_collection']))
        form.instance.game_collection.set([game_collection])
        return super(GameCreate, self).form_valid(form)


class GameUpdate(UpdateView):
    model = Game
    fields = ['game_title', 'game_description', 'game_rule', 'game_created_date', 'game_category',
              'game_rating']


class GameDelete(DeleteView):
    model = Game
    success_url = reverse_lazy('my-collection')

game_management_system/game_catalogue/templates/game_catalogue/game_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Collection</h1>

<p>Are you sure you want to delete the game: {{ game.game_title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/game_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ game.game_title }}</h1>

    <button type="button">
        <a href="{{ game.get_absolute_url }}/delete/">Delete Game</a>
    </button>
    <button type="button">
        <a href="{{ game.get_absolute_url }}/edit/">Edit Game</a>
    </button>


    <p><strong>Game Description:</strong> {{ game.game_description }}</p> <!-- author detail link not yet defined -->
    <div style="margin-left:20px;margin-top:20px">
        <hr>
        <p><strong>Game Rule:</strong> {{ game.game_rule }}</p>
        <p><strong>Game Created Date:</strong> {{ game.game_created_date }}</p>
        <p><strong>Game Category:</strong> {{ game.game_category }}</p>
        <p><strong>Game Rating:</strong> {{ game.game_rating }}</p>
    </div>
{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/game_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/gamecollection_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Collection</h1>

<p>Are you sure you want to delete the game collection: {{ game_collection }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/gamecollection_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Game Collection: {{ gamecollection.collection_name }}</h1>

    <button type="button">
        <a href="{{ gamecollection.get_absolute_url }}/delete/">Delete Collection</a>
    </button>
    <button type="button">
        <a href="{{ gamecollection.get_absolute_url }}/update/">Update Collection</a>
    </button>
    <button type="button">
        <a href="{{ gamecollection.get_absolute_url }}/create/">Create Game</a>
    </button>

    <p><strong>Collection Description:</strong> {{ gamecollection.collection_description }}</p>
    <!-- author detail link not yet defined -->
    <div style="margin-left:20px;margin-top:20px">
        <h4>Search Game Collection</h4>
        {% if gamecollection.game_set.all %}
            <form action="{{ request.path }}" method="get">
                <input id="al-search" type="text"
                       name="game_name" value="{{ request.GET.account }}"
                       class="form-control"/>
                <input type="submit"
                       value="Game Title Search" class="btn btn-success"/>
            </form>
            <form action="{{ request.path }}" method="get">
                <input id="al-search" type="text"
                       name="game_category" value="{{ request.GET.account }}"
                       class="form-control"/>
                <input type="submit"
                       value="Game Category Search" class="btn btn-success"/>
            </form>
            <form action="{{ request.path }}" method="get">
                <input id="al-search" type="text"
                       name="game_description" value="{{ request.GET.account }}"
                       class="form-control"/>
                <input type="submit"
                       value="Game Description Search" class="btn btn-success"/>
            </form>
            {% for game in filtered_games %}
                <hr>
                <p><strong><a href="{{ game.get_absolute_url }}">{{ game.game_title }}</a></strong></p>
                <p><strong>Game Category:</strong> {{ game.game_category }}</p>
                <p><strong>Game Rating:</strong> {{ game.game_rating }}</p>
                <p><strong>Game Description:</strong> {{ game.game_description }}</p>
                <button type="button">
                    <a href="{{ game.get_absolute_url }}/update/">Update Game</a>
                </button>
                <button type="button">
                    <a href="{{ game.get_absolute_url }}/delete/">Delete Game</a>
                </button>

            {% endfor %}
        {% else %}
            <p>There are no Games in your account.</p>
        {% endif %}

    </div>
{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/gamecollection_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/gamecollection_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Game Collection List</h1>
  {% if gamecollection_list %}
  <ul>
    {% for collection in gamecollection_list %}
      <li>
        <a href="{{ collection.get_absolute_url }}">{{ collection.collection_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no collection in your account.</p>
  {% endif %}
{% endblock %}

game_management_system/game_catalogue/templates/game_catalogue/gamecollection_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Collections</h1>
    <button type="button">
        <a href="{% url 'game-collection-create' %}">Create Collection</a>
    </button>
    <p>Wonderful Collections</p>

    {% if gamecollection_list %}
        <ul>
            {% for collection in gamecollection_list %}
                <hr>
                <p><strong><a href="{{ collection.get_absolute_url }}">{{ collection.collection_name }}</a></strong></p>
                <p><strong>Description:</strong> {{ collection.collection_description }}</p>
            {% endfor %}
        </ul>

    {% else %}
        <p>There are no games owned.</p>

    {% endif %}
{% endblock %}